name: flutter_catalogo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  # ... otras dependencias
  path_provider: ^2.1.3
  file_picker: ^10.3.3
  path: ^1.9.1
  shared_preferences: ^2.2.3
# ... otras dependencias
  math_expressions: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon_ktalog.png
    - assets/productos.json
    - assets/
    - assets/productos_imagenes/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_ktalog.png"
