name: flutter_catalogo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.12.0
  pdf: ^3.11.3
  path_provider: ^2.1.3
  file_picker: ^9.0.0
  path: ^1.9.1
  shared_preferences: ^2.2.3
# ... otras dependencias
  math_expressions: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/isotipo.png
    - assets/productos.json
    - assets/
    - assets/productos_imagenes/
